name: Continues Integration
on: 
  push:
    branches:
      - 'new-dev'
jobs:
  
  Build-app-CI:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python vulnerable-flask-app.py &
      - name: Test curl
        run: curl http://127.0.0.1:8081/get_users?hostname=ls

  SAST:
    runs-on: ubuntu-latest
    needs: Build-app-CI
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          path: new-dev
      - uses: AppThreat/sast-scan-action@v1.0.0
        with:
          output: reports
          type: "python"
      - uses: actions/upload-artifact@v1.0.0
        if: always()
        with:
          name: reports
          path: reports

  DAST:
    name: DAST
    continue-on-error: true
    needs: SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Dastardly Action Step
        continue-on-error: true
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'http://103.31.38.112:8081/user/test'
      
      - name: Publish Test Report with JUnit
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/dastardly-report.xml'
          require_tests: true
