name: Continues Integration
on: 
  push:
    branches:
      - 'none'
jobs:
  
  Build-app:
    name: Run the test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python vulnerable-flask-app.py &
      - name: Test curl
        run: curl http://127.0.0.1:8081

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            REPO_URL=git@github.com:acdk2662/Vulnerable-Flask-App.git
            LIVE_DIR=/home/acdk/Vulnerable-Flask-App
            echo "Pulling repository live..."
            mkdir -p $LIVE_DIR
            cd $LIVE_DIR
            git init
            git remote add origin $REPO_URL
            git pull origin main
            bash /home/acdk/config/killApp.sh && python3 /home/acdk/Vulnerable-Flask-App/vulnerable-flask-app.py &
            echo "On Production"

      
      # - name: Archive production artifgacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test
      #     path: '**/dist/dastadly-report.xml'

      # - name: artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: test
      #     path: '**/dist/dastabdly-report.xml'

    # - name: executing remote ssh commands using password
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     password: ${{ secrets.PASSWORD }}
    #     port: ${{ secrets.PORT }}
    #     script: bash /home/acdk/config/killApp.sh && python3 /home/acdk/Vulnerable-Flask-App/vulnerable-flask-app.py &

    # - name: create xml placholder file
    #   run: |
    #     touch report_xml.xml
    #     chmod a+w report_xml.xml

    # - name: owasp-scan
    #   uses: zaproxy/action-baseline@v0.9.0
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN}}
    #     docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
    #     target: ${{ secrets.TARGET }}x
    #     fail_action: false
    #     cmd_options: "-x ~/report_xml.xml"


