name: DEPLOY TO SERVER
on: 
  push:
    branches:
      - 'main'
jobs:

  build-app:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: bash /home/acdk/config/killApp.sh && python3 /home/acdk/Vulnerable-Flask-App/vulnerable-flask-app.py &

    - name: create xml placholder file
      run: |
        touch report_xml.xml
        chmod a+w report_xml.xml

    - name: owasp-scan
      uses: zaproxy/action-baseline@v0.9.0
      with:
        token: ${{ secrets.GITHUB_TOKEN}}
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        target: ${{ secrets.TARGET }}
        fail_action: false
        cmd_options: "-x ~/report_xml.xml"

    - name: artifact
      uses: actions/download-artifact@v3
      with:
        name: download
        path: ~/report_xml.xml

