name: Environment DEV
on: 
  push:
    branches:
      - 'dev'
jobs:
  
  CI:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python vulnerable-flask-app.py &
      - name: Test curl
        run: curl http://127.0.0.1:8081
  
  SAST:
    name: Static Analyst Security Testing
    needs: CI
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      #   with:
      #     path: new-dev
      - uses: AppThreat/sast-scan-action@v1.0.0
        with:
          output: reports
          type: "python"
      - uses: actions/upload-artifact@v1.0.0
        if: always()
        with:
          name: reports
          path: reports

  DAST:
    needs: SAST
    name: Dynamiccc Analysist Security Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Dastardly Action Step
        continue-on-error: true
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://google.com'
      
      - name: Publish Test Report with JUnit
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/dastardly-report.xml'
          require_tests: true

  CD:
    needs: DAST
    name: Delivery
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            REPO_URL=git@github.com:acdk2662/Vulnerable-Flask-App.git
            LIVE_DIR=/home/acdk/Vulnerable-Flask-App
            echo "Pulling repository live..."
            mkdir -p $LIVE_DIR
            cd $LIVE_DIR
            git init
            git remote add origin $REPO_URL
            git pull origin main
            bash /home/acdk/config/killApp.sh && python3 /home/acdk/Vulnerable-Flask-App/vulnerable-flask-app.py &
            echo "On Production"

      
      # - name: Archive production artifgacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test
      #     path: '**/dist/dastadly-report.xml'

      # - name: artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: test
      #     path: '**/dist/dastabdly-report.xml'

    # - name: executing remote ssh commands using password
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     password: ${{ secrets.PASSWORD }}
    #     port: ${{ secrets.PORT }}
    #     script: bash /home/acdk/config/killApp.sh && python3 /home/acdk/Vulnerable-Flask-App/vulnerable-flask-app.py &

    # - name: create xml placholder file
    #   run: |
    #     touch report_xml.xml
    #     chmod a+w report_xml.xml

    # - name: owasp-scan
    #   uses: zaproxy/action-baseline@v0.9.0
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN}}
    #     docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
    #     target: ${{ secrets.TARGET }}x
    #     fail_action: false
    #     cmd_options: "-x ~/report_xml.xml"


