name: DEPLOY TO SERVER
on: 
  push:
    branches:
      - 'main'
jobs:

  build-app:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: bash /home/acdk/config/killApp.sh && python3 /home/acdk/Vulnerable-Flask-App/vulnerable-flask-app.py &
    
    - name: owasp scaN
      uses: zaproxy/action-baseline@v0.2.0
      with:
        token: ${{ secrets.ISSUES_TOKEN }}
        target: ${{ secrets.TARGET }}
