name: Example workflow using Snyk
on: 
  push:
    branches:
      - 'new-dev'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: AppThreat/sast-scan-action@v1.0.0
        with:
          output: reports
          type: "python"
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: reports
          path: reports