name: SSH Login

on:
  push:
    branches:
      - main

jobs:
  ssh_login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: SSH into Server
      run: |
        ssh -i ~/.ssh/id_rsa user@34.133.17.230 "ls -lah"
