name: SSH Login

on:
  push:
    branches:
      - none

jobs:
  ssh_login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        eval "$(ssh-agent -s)"
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    
    - name: Set up Passphrase
      run: |
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa.pub

    - name: Set up Passphrase
      run: |
        echo "${{ secrets.SSH_PASSPHRASE }}" > ~/.ssh/passphrase
        chmod 600 ~/.ssh/passphrase

    - name: SSH into Server with Passphrase
      run: |
        ssh-add ~/.ssh/id_rsa < ~/.ssh/passphrase
        ssh -i ~/.ssh/id_rsa user@34.133.17.230 "ls -lah"
